Fsd auto installing dummy
OperationSpark/opspark pull request #61
Opened 2022-07-27 16:32 UTC by Wyndelle

Added dummyData for Projects
Recursively installing projects

2022-07-27 16:36 UTC, jmconnor3 requested changes

2022-07-27 16:36 UTC, jmconnor3 commented on controller/projects.js
> +            if (confirm.in5stall) return res(project);
did you mean to put a 5 here?

2022-07-27 16:36 UTC, jmconnor3 commented on test/test-auto-install-projects.js
> +describe.only('#installProject()', function () {
remove .only when you push up

2022-07-27 16:36 UTC, jmconnor3 commented on test/test-test.js
> +  // describe('#grabTests()', function () {
why is this commented out?

2022-07-27 16:36 UTC, jmconnor3 commented on test/test-test.js
>      it('should install package.json if necessary', function (done) {
You should refactor this test so it checks for each project like the test above it.

2022-08-01 18:04 UTC, gregthompson27 approved these changes

2022-08-02 14:08 UTC, merged